//
//  ScoreKit.h
//  ScoreDemo
//
//  Created by pengxianhe on 15/5/17.
//  Copyright (c) 2015 747.cn. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ScoreKit : NSObject

// Drawing Methods
+ (void)drawScoreStarWithFrontColor: (UIColor*)frontColor;
+ (void)drawScoreViewWithFrame: (CGRect)frame frontColor: (UIColor*)frontColor fillColor: (UIColor*)fillColor backColor: (UIColor*)backColor scoreLevel: (CGFloat)scoreLevel;

@end
